import type { NextPage } from 'next';
import Head from 'next/head';
import Toggle from '../components/Toggle';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-screen flex flex-col items-center justify-center  bg-white dark:bg-black">
        <h1 className="text-3xl font-bold text-blue-500 dark:text-red-500">
          Hello world!
        </h1>
        <Toggle />
      </main>
    </div>
  );
};

export default Home;
